### ISSUE TITLE
MD5 sum is not matching on Ubuntu download

### ISSUE THREAD

**Issue by zachfeldman** [eyecreate/ubuntu-chromebook-installer#16]
I saw the past two issues about this. However, I'm using a 16GB Kingston USB drive and it says that you need at least a 1gb drive in those issues so I don't think that's the problem.

When I try to comment out the exit statement in the script and run anyway, I get "Read-only file system" logs output for everything that runs.

Then when I try to boot into Ubuntu, I get to the SeaBIOS screen but it just says, "No bootable device."

**Comment by rdgRmCore** [comment]
@zachfeldman 

I experienced the same symptoms you are reporting this week. (MD5 didn't match, read only file system error, system wouldn't boot) In my case, I needed to delete the tmp directory that is underneath the ubuntu-chromebook-installer-master directory. This caused the script to download ubuntu again. My analysis was that my download got corrupted somehow. Thus the MD5 didn't match and the system wouldn't boot probably.

I hope this helps.

**Comment by zachfeldman** [comment]
Awesome thanks @rdgRmCore ! What's the best way to wipe the Chromebook completely (reset partitions as well) so I can start from scratch?

**Comment by rdgRmCore** [comment]
@zachfeldman 

If you want to wipe your Chromebook, follow this procedure:

https://support.google.com/chromebook/answer/1080595?hl=en

Be advised that you will probably need a spare thumb drive and possibly a spare computer to create the recovery media. You may also fall under the case of "I don't see the "Chrome OS is missing or damaged" message, but I want to reinstall my system"

Having said that, you don't necessarily need to completely wipe your chromebook if the only problem is a bad md5sum. The partitioning step may have worked just fine all you may need to do is rerun the install script with a good download of Ubuntu.

**Comment by zachfeldman** [comment]
Ok so, I was able to fix this issue by redownloading! Thanks!
