### ISSUE TITLE
Caps_Lock and Search (Super_L)

### ISSUE THREAD

**Issue by phreshbeatz** [eyecreate/ubuntu-chromebook-installer#18]
Hi, great work on this stuff.  I struggled a great deal with getting the search key to function as Caps_Lock, but FINALLY SOLVED IT UGH.
I think other users might find it helpful if you added the following to ~/.xbindkeysrc

"xdotool key Caps_Lock"
m:0x0 + c:225
"xdotool keyup ctrl+XF86Search; xdotool key Super_L; xdotool keydown ctrl"
m:0x4 + c:225

**Comment by eyecreate** [comment]
Thanks for sharing this. I'm not sure this is the right thing to make default because some commands could be lost without a super key. It can be added to the readme, though, so those wanting alternative functions could have time saved.

**Comment by phreshbeatz** [comment]
I see.  I know on my HP 14 there is no Super key, and with the existing 
commands there is no Super key alternative, which is why I added that 
command on my own machine.

**Comment by eyecreate** [comment]
Interesting. Guess since the search key on my c720 functioned as a super key by default, I assumed that was common practice. For now, it is best where it is, but it could be a custom device script in the future.
